In [ ]:
import numpy as np


In [ ]:
l=[1,2,3,4,5]

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([1, 2, 3, 4, 5])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
l2=[[1,2],[3,4]] #basicallly it's a list containing two sub-list

In [ ]:
np.array(l2)

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.matrix(l)

In [ ]:
b


matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
#matrix cant be converted to array becos matrix is subset of array
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.fromfunction(lambda i,j: (i==j),(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j: (i*j) ,(3,3) )

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([], dtype=float64)

In [ ]:
np.fromstring('234 234' , sep=" ")

array([234., 234.])

In [ ]:
np.fromstring('4,5' , sep=",")

array([4., 5.])

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([1, 2, 3, 4, 5])

In [ ]:
ar.ndim

1

In [ ]:
ar2 = np.array([[1,2,3],[3,4,5]])

In [ ]:
ar2

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
ar2.ndim

2

In [ ]:
ar.shape

(5,)

In [ ]:
ar2.shape #(2,3) ouput means it has 2 rows and 3 columns

(2, 3)

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(5)) #range always take integer as an input

[0, 1, 2, 3, 4]

In [ ]:
np.arange(3.4,8.9)

array([3.4, 4.4, 5.4, 6.4, 7.4, 8.4])

In [ ]:
np.arange(3.4,8.9,0.9)

array([3.4, 4.3, 5.2, 6.1, 7. , 7.9, 8.8])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2)) # it gives us 3 arrays/matrices which has 4 rows and 2 columns
#use in image

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
on = np.ones((2,3,3)) #it creates 3x3 ke 2 matrices

In [ ]:
on

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
on*5


array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [ ]:
np.empty((3,5))

array([[4.80598770e-310, 0.00000000e+000, 5.58410408e-091,
        4.79243676e-322, 6.88610512e-310],
       [6.88610514e-310, 5.28555805e+180, 4.42132230e-062,
        4.57842046e-071, 4.46470451e-086],
       [3.35760322e-143, 9.30350598e+199, 4.24941018e-086,
        8.69421719e-316, 9.48606040e-322]])

In [ ]:
np.eye(4) # it return identity matrixes

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(2, 4 , 20) #between 2 and 4 it produces 20 data

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [ ]:
np.logspace(2,5,10) #it return 10 data between 2 and  5

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [ ]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
arr = np.random.randn(3,4)

In [ ]:
arr

array([[-1.16485314,  0.43280803, -1.0977201 ,  2.07512071],
       [ 0.57259596, -0.21413981, -0.43515279,  0.5100264 ],
       [-0.78333282,  0.23616589,  0.84124762, -0.95743677]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr)

0         1         2         3
0 -1.164853  0.432808 -1.097720  2.075121
1  0.572596 -0.214140 -0.435153  0.510026
2 -0.783333  0.236166  0.841248 -0.957437

In [ ]:
np.random.rand(3,4)

array([[0.43015655, 0.67007572, 0.76002986, 0.11915023],
       [0.55346805, 0.37787944, 0.14046757, 0.97426849],
       [0.59216418, 0.9330939 , 0.68795226, 0.33618913]])

In [ ]:
pd.DataFrame(np.random.randint(1,110,(3,4)))

0   1    2    3
0  104  32   60  105
1    8   6  102  105
2   30  43   83   43

In [ ]:
np.random.rand(3,4)

array([[0.80554242, 0.45777402, 0.98902289, 0.24472537],
       [0.50263302, 0.6337405 , 0.61918864, 0.37451242],
       [0.97084787, 0.98119493, 0.82705488, 0.72545448]])

In [ ]:
arr = np.random.rand(3,4)

In [ ]:
arr


array([[0.11876505, 0.59805656, 0.17160707, 0.40858428],
       [0.66043146, 0.61700816, 0.12679185, 0.82408586],
       [0.63111064, 0.70394104, 0.24375859, 0.84605589]])

In [ ]:
arr1 = arr.reshape(6,2)

In [ ]:
arr1

array([[0.11876505, 0.59805656],
       [0.17160707, 0.40858428],
       [0.66043146, 0.61700816],
       [0.12679185, 0.82408586],
       [0.63111064, 0.70394104],
       [0.24375859, 0.84605589]])

In [ ]:
arr1[2][1]


0.6170081638416676

In [ ]:
arr = np.random.randint(1,100,(5,5))

In [ ]:
arr

array([[97, 91, 69, 85, 90],
       [17, 39, 18, 48, 78],
       [24, 21, 49, 69,  2],
       [52, 54, 77, 92,  4],
       [23, 42, 69, 74, 24]])

In [ ]:
arr[arr>50]

array([97, 91, 69, 85, 90, 78, 69, 52, 54, 77, 92, 69, 74])

In [ ]:
#arr[2:4 , [1:2]]

In [ ]:
arr1 =np.random.randint(1,3,(3,3))
arr2 =np.random.randint(1,3,(3,3))

In [ ]:
arr1

array([[2, 1, 1],
       [2, 2, 2],
       [2, 1, 1]])

In [ ]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [1, 2, 2]])

In [ ]:
arr1+arr2


array([[4, 3, 3],
       [3, 4, 4],
       [3, 3, 3]])

In [ ]:
#for matrix multiplication
arr1@arr2

array([[ 6,  8,  8],
       [ 8, 12, 12],
       [ 6,  8,  8]])

In [ ]:
#numpy part 2  - ARRAY manipulation

In [ ]:
import numpy as np

In [ ]:
arr =np.random.randint(1,10,(3,4))

In [ ]:
arr

array([[6, 6, 3, 7],
       [7, 7, 2, 6],
       [3, 6, 5, 3]])

In [ ]:
arr.reshape(6,2)

array([[6, 6],
       [3, 7],
       [7, 7],
       [2, 6],
       [3, 6],
       [5, 3]])

In [ ]:
arr.reshape(2,6)

array([[6, 6, 3, 7, 7, 7],
       [2, 6, 3, 6, 5, 3]])

In [ ]:
#arr.reshape(2,7)-wont work because there are total 12 elements in our array

In [ ]:
arr.T

array([[6, 7, 3],
       [6, 7, 6],
       [3, 2, 5],
       [7, 6, 3]])

In [ ]:
arr.flatten() #flatten converts 2d array to 1d

array([6, 6, 3, 7, 7, 7, 2, 6, 3, 6, 5, 3])

In [ ]:
arr1 = np.array([1,2,3,3,4])

In [ ]:
arr1.ndim

1

In [ ]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [ ]:
#np.squeeze(arr)

In [ ]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [ ]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
#numpy binary opertions

In [ ]:
arr1 = np.random.randint(1,10,(3,4))

In [ ]:
arr2 = np.random.randint(1,10,(3,4))

In [ ]:
arr1

array([[2, 1, 1, 7],
       [5, 6, 5, 8],
       [5, 9, 3, 8]])

In [ ]:
arr2

array([[4, 5, 6, 2],
       [2, 9, 9, 9],
       [9, 4, 8, 5]])

In [ ]:
arr1+arr2

array([[ 6,  6,  7,  9],
       [ 7, 15, 14, 17],
       [14, 13, 11, 13]])

In [ ]:
arr1*arr2

array([[ 8,  5,  6, 14],
       [10, 54, 45, 72],
       [45, 36, 24, 40]])

In [ ]:
arr1/arr2

array([[0.5       , 0.2       , 0.16666667, 3.5       ],
       [2.5       , 0.66666667, 0.55555556, 0.88888889],
       [0.55555556, 2.25      , 0.375     , 1.6       ]])

In [ ]:
arr1%arr2

array([[2, 1, 1, 1],
       [1, 6, 5, 8],
       [5, 1, 3, 3]])

In [ ]:
arr1**arr2

array([[       16,         1,         1,        49],
       [       25,  10077696,   1953125, 134217728],
       [  1953125,      6561,      6561,     32768]])

In [ ]:
arr1 & arr2

array([[0, 1, 0, 2],
       [0, 0, 1, 8],
       [1, 0, 0, 0]])

In [ ]:
#string function


In [ ]:
arr =np.array(['sudhanshu','gautii'])

In [ ]:
arr

array(['sudhanshu', 'gautii'], dtype='<U9')

In [ ]:
np.char.upper(arr)

array(['SUDHANSHU', 'GAUTII'], dtype='<U9')

In [ ]:
np.char.title(arr)

array(['Sudhanshu', 'Gautii'], dtype='<U9')

In [ ]:
np.sin(arr1)

array([[ 0.90929743,  0.84147098,  0.84147098,  0.6569866 ],
       [-0.95892427, -0.2794155 , -0.95892427,  0.98935825],
       [-0.95892427,  0.41211849,  0.14112001,  0.98935825]])

In [ ]:
np.cos(arr1)

array([[-0.41614684,  0.54030231,  0.54030231,  0.75390225],
       [ 0.28366219,  0.96017029,  0.28366219, -0.14550003],
       [ 0.28366219, -0.91113026, -0.9899925 , -0.14550003]])

In [ ]:
np.tan(arr1)

array([[-2.18503986,  1.55740772,  1.55740772,  0.87144798],
       [-3.38051501, -0.29100619, -3.38051501, -6.79971146],
       [-3.38051501, -0.45231566, -0.14254654, -6.79971146]])

In [ ]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.        , 0.84509804],
       [0.69897   , 0.77815125, 0.69897   , 0.90308999],
       [0.69897   , 0.95424251, 0.47712125, 0.90308999]])

In [ ]:
np.exp(arr1)

array([[7.38905610e+00, 2.71828183e+00, 2.71828183e+00, 1.09663316e+03],
       [1.48413159e+02, 4.03428793e+02, 1.48413159e+02, 2.98095799e+03],
       [1.48413159e+02, 8.10308393e+03, 2.00855369e+01, 2.98095799e+03]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        , 2.64575131],
       [2.23606798, 2.44948974, 2.23606798, 2.82842712],
       [2.23606798, 3.        , 1.73205081, 2.82842712]])

In [ ]:
np.mean(arr1)

5.0

In [ ]:
np.std(arr1)

2.6457513110645907

In [ ]:
#sorting , searching and counting functions

In [ ]:
import numpy as np

In [ ]:
arr = np.array([6,7,8,9,1,2,3])

In [ ]:
arr

array([6, 7, 8, 9, 1, 2, 3])

In [ ]:
np.sort(arr)

array([1, 2, 3, 6, 7, 8, 9])

In [ ]:
np.searchsorted(arr,34)

7

In [ ]:
arr1 = np.array([0,23,4,5,2,34,56,78,12,45,0,0,0,0])

In [ ]:
np.count_nonzero(arr1)

9

In [ ]:
np.where(arr1>6) #it tells the index where >6 values are there

(array([1, 5, 6, 7, 8, 9]),)

In [ ]:
# numpy - matrix library

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:

nm.eye((5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#numpy - linear algebra

In [ ]:
arr1 = np.random.randint([[1,10],[3,4]])

In [ ]:
arr2 = np.random.randint([[1,10],[3,4]])

In [ ]:
arr1

array([[0, 6],
       [2, 3]])

In [ ]:
arr2

array([[0, 4],
       [0, 3]])

In [ ]:
np.dot(arr1,arr2)

array([[ 0, 18],
       [ 0, 17]])

In [ ]:
arr1@arr2

array([[ 0, 18],
       [ 0, 17]])